version: '3'

services: 

  mongo:
    image: mongo
    container_name: bb_mongo
    networks:
      - app-tier
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    env_file: 
      - .env

  python:
    container_name: bb_python
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mongo
    networks:
      - app-tier
    command:
      bash -c "tail -f /dev/null"
    volumes:
      - ./app:/app
      - ./projoutput:/projoutput
    env_file: 
      - .env
  
  web:
    image: nginx
    container_name: bb_web
    ports:
      - 8080:80
    volumes:
      - ./projoutput:/usr/share/nginx/html
    networks:
      - app-tier
    env_file: 
      - .env

networks:
  app-tier:
    driver: bridge