version: '3'

services: 

  mongo:
    image: mongo
    networks:
      - app-tier
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017

  python:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mongo
    networks:
      - app-tier
    command:
      bash -c "tail -f /dev/null"
    volumes:
      - ./app:/app
      - ./projoutput:/projoutput
  
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./projoutput:/usr/share/nginx/html
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge